# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: StreamX Docs Vuepress CI

on:
  push:
    branches: main
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: Al-assad/streamx-docs
        TARGET_BRANCH: master
        BUILD_SCRIPT: npm install && npm run build
        BUILD_DIR: .vuepress/dist/
